### ISSUE TITLE
Lengthy load times

### ISSUE THREAD

**Issue by robtweed** [PulseTile/PulseTile-React-Core#117]
The current UI for the PHR requires a very large download of JavaScript - currently nearly 10Mb.  This takes a considerable amount of time and makes the PHR appear very sluggish to start up.

Is there any way to reduce the JavaScript size, eg through compression etc.?  Alternatively can it be broken into parts that are loaded on demand (perhaps a more difficult thing to do with a React app which tends to compile to a single large monolithic bundle) ?

**Comment by anna-otrokhova** [comment]
@robtweed 
Thank you for raising this issue.
Actually, LeedsPHR version has already these changes and the size of js files was reduced twice. 
We've just missed it by pushing the last changes, but we've just renewed it with these changes. Could you please check it and move them to the needed machine?

Our React version on dev server is in process of development that is the reason why the build hasn't been minified yet. We will do it after finishing our works there.

By the way, the idea of dividing the js into parts and loading on demand is great, it needs planning and time. Maybe it could be implemented later.

**Comment by kbeloborodko** [comment]
@robtweed we added code splitting to our code, so now the main bundle has been reduced to 1.9mb. This should positively affect the load time speed.

CC: @tony-shannon

**Comment by tony-shannon** [comment]
Need to use these tools to test with slow 3g

![image](https://user-images.githubusercontent.com/939996/41153655-4741109e-6b0f-11e8-9141-38db43052c93.png)

**Comment by BogdanScherban** [comment]
I checked in **slow 3G mode.** It is equal:
19.31 seconds (30,7 kB) - without Feeds RSS
22.1 seconds (186 kB) - with all Feeds

**For comparison (normal mode):**
3.89 seconds (29,9 kB) - without Feeds RSS
4 seconds (184 kB) - with all Feeds

**Comment by tony-shannon** [comment]
thanks @BogdanScherban 
Please check the behaviour of the application in slow 3G mode and document any related problems you see after checking several times.
thanks
Tony

**Comment by BogdanScherban** [comment]
@tony-shannon 
I checked several times for both cases (with/without Feeds), so:
- the same result 19-23 sec for both cases, if we reload the page
- 1-2 minutes when we reload page with cache cleaning.

The main part of this time is spent on main.JS and style.css files loading
(look at image)

But loading time of our request (Demographics, Feeds, Headings etc.) isn't more then 2-3 seconds for each.
![screenshot from 2018-06-12 16-26-38](https://user-images.githubusercontent.com/39263134/41293493-11a7d1aa-6e5e-11e8-9e62-2e09947674bf.png)

**Comment by BogdanScherban** [comment]
@robtweed 
Rob, Patient Summary page loading time equals 1...2 minutes at slow 3G mode.
The main part of this time is loading of files main.js and style.css

Is there any way to reduce loading time from the client side?

**Comment by tony-shannon** [comment]
Thanks @BogdanScherban 

I suggest we ask @kbeloborodko that question

thanks

**Comment by kuvakina** [comment]
@tony-shannon 
Update on 05.07.2018

Bogdan had an idea how we can reduce loading time. He proposed to repeat loading time checking after non-core plugins extracting. Unfortunately, loading time (in slow 3G) isn't changed.

We'll look further at what we can do to reduce time.

**Comment by BogdanScherban** [comment]
@tony-shannon  @kbeloborodko 

I reduced load time at 3G mode. Now it 40-50 sec (in comparison with 1-2 min early), after browser data cleaning. What I did:
1) minimized CSS-files
2) removed some plugins from build which aren't critical in imagination.

We can see the difference of file sizes at screenshots

![01](https://user-images.githubusercontent.com/39263134/42869991-484c9d20-8a7f-11e8-9622-5ab86cb60829.png)
![02](https://user-images.githubusercontent.com/39263134/42869992-486d6488-8a7f-11e8-9f1f-e351de84564b.png)

Besides this, I tried to reduce files sizes by other ways (plugins splitting and removing).
But unfortunately in these cases build doesn't work generally.

So, it is enough (45 sec at slow 3G-mode) or it is necessary to reduce loading time more?

**Comment by kuvakina** [comment]
@tony-shannon 
I want to notice, that load time - 40-50 seconds is for slow 3G speed lesser than 250kb/s. It was tested in Chrome emulator.

**Comment by tony-shannon** [comment]
thanks

This sounds good, as discussed today, lets see if we can do quick bandwidth
test and trigger messages accordingly

Tony

**Comment by tony-shannon** [comment]
msg from Alexandra: 
"We previously talked that we should add messages when app loads too long with slow 3G. 
I wanted to ask, how critical is this?" 

this would be good to do soon

**Comment by kuvakina** [comment]
Ok, then we'll see how to add messages after we make Helm PHR theme as a plugin

**Comment by PhilBarrett** [comment]
Going back into testing. Then we need to agree the rules on when the messages appear.

**Comment by kuvakina** [comment]
Alyona had searched regarding this issue and found the next solutions:

**Comment by kuvakina** [comment]
UPD:

Alyona made it that by using Toastr functionality, we have a message about slow connection, if site take a time to load, and it disappear when the site loaded:

**Comment by PhilBarrett** [comment]
@kuvakina thanks for the update. I think the bigger issue with this is that there appears to be nothing happening from clicking to log in to the application, for 2minutes plus, then QEWD is triggered and data retrieved. That doesn't look right, can you have a look into this please?

**Comment by kuvakina** [comment]
Tested the app again.

Now the site loads 13-22 seconds: https://www.screencast.com/t/ngO7gkoJV

Also get the error with token (at the beginning of the video) #159 

@tony-shannon @PhilBarrett

**Comment by Alena1508** [comment]
I found two ways how to show message about bad connections. We can use Toastr library (https://codeseven.github.io/toastr/). The message "Wait...Your connection is slow" will be shown before the DOM is load.
https://drive.google.com/open?id=1vykW31WaBfRyoNv_8NDpxC4oDOIt76mZ

But I checked that it is enough only to add CSS-styles which are required for this message. And don't add to our project all functionality of Toastr library. You can see, that result is the same: 
https://drive.google.com/file/d/1fxFyzA1UkvpKWAdp-SoucviW9rA31WrH/view?usp=sharing

What do you think about it?

We can't solve this issue with React Notification System library, because its functionality start to work only after DOM will be loaded.

@tony-shannon @PhilBarrett

**Comment by simongamester** [comment]
Tony, Phil and I had another idea which might be even more light-weight: Displaying a loader in CSS, rendered before the main.js and styles.css load in.

In order to do this, we'd need to run some custom js and css which would invoke page render before the DOM has finished loading.

https://github.com/filamentgroup/loadCSS

The example above could be implemented into the index.html and would allow us to 'execute' a custom css file very early on. Inside this we could then display a loader graphic which is replaced by a message asking users to continue waiting i.e. 'This may take some time...' .

**Comment by BogdanScherban** [comment]
@simongamester 

Simon, I'm not sure, that this variant will work more quickly than variant #2 from Alena.

Why? Because in this case we should firstly load all functionality of this library.

In variant #2 we should load only required CSS-rules. For this reason it will work quickly. It is very important because connection will be bad and the message should be occurred ASAP.

**Comment by Alena1508** [comment]
I  solved this problem without using any libraries. This is pull requests: 1) https://github.com/PulseTile/PulseTile-React-Core/pull/251;   2) https://github.com/PulseTile-Plugins/Plugin-Helm-PHR-Theme/pull/13

**Comment by kuvakina** [comment]
We tried to make a video how messages about slow connection look like, but now the site loads fast enough, even in 2g.
We have a suggestion, that it because we don't use images and because we separate theme.

See the video, that record mobile version in 2g (current Helm version):
https://www.screencast.com/t/ES3ZDP4tPkE1

**Comment by PhilBarrett** [comment]
Thanks @kuvakina , we'll close this issue off now.
