### ISSUE TITLE
issue with servers is faced when End2End tests are run

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#129]
From time to time ethercis servers are unavailable and we noticed that, when it happens, creation or/and editing functionality stops working properly. Here are some examples of this
malfunction:

Video test running showcase: https://drive.google.com/file/d/1f--TllLlxZ1Nab6t0UheERM9LE64hXXM/view 

Note: When test running started ethercis servers were available: http://prntscr.com/hy2q90, but during the tests they became unavailable again: https://prnt.sc/iiq9l6 , https://prnt.sc/iiq9tn and so on.

Though when we run tests one by one sometimes it could work as it should (to record this video with a positive scenario I had to run tests multiple times to catch the ethercis servers)  :

1) Vaccination test video: https://drive.google.com/file/d/190QNah9Fh0XKE63fm-f9SS_MSDVHY139/view 
2) Personal Notes test video: https://drive.google.com/file/d/1Tfaxq8fTYWatX-sFGQkOJGUjTwQ4GRsc/view 
3) Allergies test video: https://drive.google.com/file/d/1vHCNqEuBXA9Wav-dtJrk6M7PzMnypBA0/view 
4) Problems/Diagnosis test video: https://drive.google.com/file/d/1YaKuC2GeBtQo1qQp7ZDr4t0FD0EFllaJ/view 

We assume that there is some issue with performance of the DB (or ethercis server) or restriction of incoming traffic. This is a frequent situation that during the tests backend stops working
properly.
Could we ask Rob to look at this issue?

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/86

**Comment by tony-shannon** [comment]
well documented issue
thanks Anna
T

**Comment by robtweed** [comment]
Without being able to watch what happens on the QEWD middle tier during a set of tests, it's difficult to know what the problem is.  However, if you're saying that when EtherCIS isn't available, then the tests don't run, it's not really surprising, since the middle tier won't be able to post or update records on EtherCIS.  The questions seem to be:

1) Is there a problem with the QEWD Middle tier when running the tests?  I won't know unless we can co-ordinate a set of tests during which I can monitor the middle tier log.  I don't believe there are any problems that testing would introduce that you'd not have seen during normal use.

2) Is there a problem with EtherCIS being unable to cope with the activity generated by the tests?  This is my suspicion, but once again we'd need to co-ordinate a set of tests so I can observe the responses from EtherCIS.  If the problem turns out to be an EtherCIS one, then we need to give Christian the evidence and ask him to investigate

**Comment by anna-otrokhova** [comment]
@robtweed 
I will be glad to assist you when you are ready to check the log (I will run tests from my side )

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Update. 
We tested it with Rob today and Rob found that it looks like EtherCIS decides there's too much activity and returns this "Access to ehrserver denied" 

Rob captured the log and he should have enough to work with in that log file - he is going to see what he can discover.

**Comment by anna-otrokhova** [comment]
Related issue: https://github.com/ethercis/ethercis/issues/104

**Comment by robtweed** [comment]
I've made changes to how sessions are controlled on EtherCIS which appears to rectify this problem

**Comment by tony-shannon** [comment]
thanks @robtweed 

@kbeloborodko can u recheck this test now please

**Comment by tony-shannon** [comment]
as all End2End tests are passing now, this can be closed
