### ISSUE TITLE
Extra Leeds PHR specific styles and images to a separate fork

### ISSUE THREAD

**Issue by kbeloborodko** [PulseTile/PulseTile-React-Core#144]

**Comment by kbeloborodko** [comment]
1. Leeds PHR specific images that are contained under src/assets/images directory should be moved to LeedsCC fork
2. _leedsPHR.scss file that is contained under src/styles/themes directory should be moved to LeedsCC fork

**Comment by tony-shannon** [comment]
move to LeedsCC repo?

Bogdan saying images are handled server side??
We need to ensure UI theme images are kept in client side repo, LeedsCC repo or another repo for theming images

**Comment by BogdanScherban** [comment]
@kbeloborodko @tony-shannon 

I tried to solve this task by the method, which is described upper. 

But it was impossible, because in this case Main and LeedsCC repositories will have different code. 
Now these two repositories are different only by one theme constant.

If we want to remove image-files and style-files from Main, we must remove all importing of these files in React-code. In opposite case project can't be build. Because image-file or style-file for ReactJS - there are module for build. 

We will have two projects with different code:
1) Main - without image-files and without images importing;
2) LeedsCC - with images and with their importing.

Now we located images at server. We don't import images - we get them by GET-request like
http://dev.ripple.foundation:8000/images/banners/allergies.jpg

In this case we can save equal code in Main and LeedsCC repositories.

**Comment by tony-shannon** [comment]
@kbeloborodko  to lead and guide us on this

**Comment by BogdanScherban** [comment]
@tony-shannon 
Hi, Tony!

We solved this problem by the follow way:
1) all non-core plugins and images were removed from the Core-repo;
2) created separate fork for LeedsCC-version;
3) added non-core plugins, which were necessary in Leeds;
4) added images to client side and inported them to React.

Changes were checked, testes and approved by Kirill.
Now this task is done.

**Comment by tony-shannon** [comment]
tthanks @BogdanScherban 
Can you explain what u mean by "added images to client side and inported them to React."

**Comment by BogdanScherban** [comment]
@tony-shannon 

Sorry, I mean 'imported'. 
We located images in client side and imported them as React-components (in LeedsCC-repo). 
In Core-repo images are absent.

**Comment by tony-shannon** [comment]
ok thanks Bogdan
what folder have u moved images to?
Thanks T

**Comment by BogdanScherban** [comment]
The same folder, which was earlier: /src/assets/images

**Comment by tony-shannon** [comment]
ok thanks

**Comment by tony-shannon** [comment]
ok to  close for now @kuvakina 
Please set up a new issue for Helm PHR theme as Plugin as per discussion
