### ISSUE TITLE
Sign out doesn't work at FireFox 60.0.2

### ISSUE THREAD

**Issue by juliashulga** [PulseTile/PulseTile-React-Core#177]
Upon clicking nothing happens , in console no errors - http://prntscr.com/jxiazh

**Comment by kuvakina** [comment]
@tony-shannon 

This bug was fixed and right we can successfully log out from Firefox. Can we conclude this task as a Done?

[The problem was a small bug with HTML markup. On Firefox an event couldn't go through (did not work out clicking on the wrapper in which the button was). Oleg moved the listener to the wrapper.]

**Comment by tony-shannon** [comment]
thanks @kuvakina 
If you say this bug is fixed, then we can close for now
thanks
Tony
