### ISSUE TITLE
Green (Main) Theme as plugin 

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-React-Core#207]
@BogdanScherban has been crafting the Helm theme plugin

> In doing so we have identified
> Core has main (green) theme by default.
> My command does the following:
> - clones HelmPHR from GitHub;
> - moves CSS and images in required places;
> - update config files, which unite theme and code.

So we need to craft a Green Theme (main theme) as a Theme PLugin
![image](https://user-images.githubusercontent.com/939996/44540575-27d5e280-a6ff-11e8-82c3-a82161862feb.png)

 
T

**Comment by kuvakina** [comment]
@tony-shannon 

Regarding this task I have a few questions:

1.
At the moment this theme set as Default. If we were to make this theme as a separate plugin, what we have to set as Default theme then? Because the project couldn't be without the theme, afaik 

2.
At the moment we are working with this plan:

1) Helm PHR theme plugin
2) UI/Data Model tidy up
3) Tour of Application
4) Brand refresh
5) Accessibility changes

And after we planned to return to documentation. 

And if we'll make this theme as a plugin, should we also do this issue after Accessibility changes or we have to give it a higher priority?

**Comment by tony-shannon** [comment]
thanks @kuvakina 
Good Q 
in reply
1) we will need a showcase demonstrator generator , similar to the Helm PHR generator
and in that Showcase this theme would be the default theme plugin

2) this task can be low priority at the moment, please ask those project management questions elsewhere, thanks

**Comment by BogdanScherban** [comment]
@tony-shannon 
What non-core plugins should be added to the showcase?

**Comment by tony-shannon** [comment]
Need to be careful here

The green theme is separate to the showcase generator.

Please clarify the question

**Comment by kuvakina** [comment]
This task is done, @tony-shannon @PhilBarrett 

Here you can see, that Core doesn't have Showcase theme: https://github.com/PulseTile/PulseTile-React-Core

**Comment by kuvakina** [comment]
This task is done, @tony-shannon @PhilBarrett 

Here you can see, that Core doesn't have Showcase theme: https://github.com/PulseTile/PulseTile-React-Core
