### ISSUE TITLE
Menu button not functioning in mobile view

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile-React-Core#232]
See above

**Comment by BogdanScherban** [comment]
This issue occurred because Core code had a condition which hide Sidebar menu in mobile mode (when screen width less than 768 px).

It was enough to remove this condition   

Menu is opened:
![mobile-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46e59b982a8e86e4deabf301b44fff9e2c4533317346f6297186e67bea442c030c0e4bf841585647a9f08a7ef0b32e6c981e5ab38532022d8c6853beb2901eb70bbb25884780b1bf894fc7e03527f5c6.png)

Menu is closed:
![mobile-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46e59b982a8e86e4ddabf301b44fff9e2c4533317346f6297186e67bea442c030c0e4bf841585647a9f08a7ef0b32e6c981e5ab38532022d8c6853beb2901eb80bbb25884780b1bf894fc7ef3423f5c6.png)

**Comment by PhilBarrett** [comment]
@BogdanScherban has this been applied and tested in the Helm theme too please?

**Comment by BogdanScherban** [comment]
yes, we've tested it in Helm

**Comment by tony-shannon** [comment]
that PR should fix #232
