### ISSUE TITLE
align Helm & Showcase themes & tidy up  branches

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-React-Core#235]
From Bogdan>
"We have one idea. Now we have two generators: Helm and Showcase. There one important difference.

Showcase uses Core without any styles, and we should install Showcase theme.
Helm uses Core with default theme (Showcase), and we install Helm-theme above it. 

So, Helm and Showcase use different branches in Core. And Helm-theme needs in Showcase as a base."

**Comment by tony-shannon** [comment]
2 issues here 
@simongamester
2 themes Showcase & Helm , need to ensure they have been done consistently
2+ branches in ReactCore repo, need tidying please

**Comment by tony-shannon** [comment]
steps?
1) merge branches?
2) merge generators?
3) move off of generators?
Simon to consider...

**Comment by simongamester** [comment]
In response to @BogdanScherban's comment above, once we've merged the develop-without-styles of core into the develop branch, both the showcase and helm themes should be using the same version of core and the same core generator.

As it stands, we now have two generator repos which both contain sub generators for:

core
feeds
top-three-things
vaccinations

https://github.com/PulseTile/PulseTile-React-Showcase-Generator/tree/master/generators
https://github.com/RippleOSI/Helm-PHR-Generator/tree/master/generators

I think these should all be moved over to a single generator repo rather than existing in two places but only once we've merged the develop-without-styles branch into the develop branch. We should probably use the showcase generator repo to house all of these sub generators.

@BogdanScherban Other than the git locations where these repos pull code from, are the sub-generators above the same?

**Comment by BogdanScherban** [comment]
@Simon, it will be more easy to have one common generator.

Right now Showcase- and Helm-generator use difference versions of Core- sub-generator.
Because Showcase- uses Core without styles and Helm- uses Core with default styles.

But we prepared all changes, which are necessary to use Core without styles in HelmPHR-generator

**Comment by BogdanScherban** [comment]
Right now we have two branches in Core:
1) develop - it is Core with styles;
2) develop-without-styles2 - it is Core without styles;

It is necessaty to merge develop with develop-without-styles2.
All our Generators (HelmPHR- and Showcase-) will use Core without styles.

**Comment by BogdanScherban** [comment]
Right now Plugin-Helm-PHR-Theme has two branches:
- master - with old HelmPHR-theme 
- develop-merge - with HelmPHR-theme after rebranding

HelmPHR-generator works with develop-merge.

**Comment by simongamester** [comment]
@tony-shannon should we move all sub generators in the helm generator over to the showcase as Bogdan suggests? Did you want to keep helm-specific stuff in its own generator?

**Comment by tony-shannon** [comment]
lets merge the branches first and come back to that after

**Comment by BogdanScherban** [comment]
This issue has been done.
Both current versions of Helm-generator and Showcase-generator use "develop" branch for Core

**Comment by PhilBarrett** [comment]
@simongamester - can you take a brief look at this please and confirm if ok to close. Thanks.

**Comment by PhilBarrett** [comment]
Reviewed, now two branches on react core, Master and Develop
