### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#254]
Dependency defined in package.json file requred updates: 

bootstrap  3.3.7 ~>  4.1.2
lodash   4.17.5 ~>  4.17.5
moment  2.18.1 ~>  2.19.3

**Comment by Alena1508** [comment]
Done

**Comment by PhilBarrett** [comment]
@kuvakina and @Alena1508 this a  isn't good enough description of the  issue and the resolution, there is no way anyone could understand this, looking back on the issue. Please can you update.

**Comment by Alena1508** [comment]
I updated dependency in package.json file:
bootstrap ~> 4.1.2
lodash ~> 4.17.5
moment ~> 2.19.3

**Comment by BogdanScherban** [comment]
This PR is necessary for this issue:
#254

The reasons on dependency conflict are:

Master branch haven't been updated with latest changes from June. It include versions before non-core plugins extraction. This version is very old for now.
Dependencies in Master branch are old too. For example, lodash in Master is 4.17.4 (old and unsafety) and in Develop 4.17.5.
For this reason @kbeloborodko suggested to update Master by merging it with Develop.

But it can't be done automatically because of conflicts. For this reason I did these steps:
1) Clone current Core from parent account;
2) Merge Master to Develop and resolve all conflicts;
3) Check by unit-tests and commited my changes;
4) Check possibility to merge my changes with parent master.
